version: "3"

services:
   misquote-of-the-day:
      build: ./misquote-of-the-day
      env_file:
        - ./.gitsecret/secrets/misquote-of-the-day.env
      environment:
        - MYSQL_HOST=mysql
      ports:
         - 8888:80
   mysql:
      build: ./mysql
      env_file:
        - ./.gitsecret/secrets/misquote-of-the-day.env
      ports:
         - 33006:3306